import uuid
from decimal import Decimal
from typing import Any
from django.conf import settings
from django.db import models
from products.models import Product


def generate_order_number() -> str:
    """Helper function returning a hex string for CharField uuid defaults."""
    return uuid.uuid4().hex


class Order(models.Model):
    """Client purchase and fulfillment orders with complete shipping details."""

    class Status(models.TextChoices):
        PENDING = "PENDING", "Pending"
        PROCESSING = "PROCESSING", "Processing"
        SHIPPED = "SHIPPED", "In Transit"
        DELIVERED = "DELIVERED", "Delivered"
        COMPLETED = "COMPLETED", "Completed"
        CANCELLED = "CANCELLED", "Cancelled"

    class PaymentStatus(models.TextChoices):
        PENDING = "PENDING", "Pending"
        ADVANCE_DONE = "ADVANCE_DONE", "Advance Done"
        HALF_DONE = "HALF_DONE", "Half Done"
        COMPLETED = "COMPLETED", "Completed"

    order_number = models.CharField(
        max_length=32,
        unique=True,
        editable=False,
        default=generate_order_number,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="orders",
    )
    shipping_address = models.ForeignKey(
        "accounts.Address",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="orders",
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING,
    )
    payment_status = models.CharField(
        max_length=20,
        choices=PaymentStatus.choices,
        default=PaymentStatus.PENDING,
        help_text="Managed by administrators in the admin panel",
    )

    # Financial breakdown
    subtotal = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=Decimal("0.00"),
    )
    shipping_cost = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=Decimal("0.00"),
    )
    total_amount = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=Decimal("0.00"),
    )

    # Shipping & Logistics breakdown
    shipping_method = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        help_text="e.g. Standard Freight, Express Air, Surface Cargo",
    )
    courier_name = models.CharField(max_length=100, blank=True, null=True)
    tracking_number = models.CharField(max_length=100, blank=True, null=True)
    tracking_url = models.URLField(max_length=500, blank=True, null=True)
    estimated_delivery = models.DateField(blank=True, null=True)
    dispatched_at = models.DateTimeField(blank=True, null=True)

    # PDF Invoice generated by staff
    invoice = models.FileField(
        upload_to="invoices/%Y/%m/",
        blank=True,
        null=True,
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def update_totals(self) -> None:
        """Calculates subtotal and total_amount from related items."""
        calculated_subtotal = sum(item.get_cost()
                                  for item in self.items.all())  # type: ignore
        self.subtotal = calculated_subtotal
        self.total_amount = calculated_subtotal + self.shipping_cost
        self.save(update_fields=["subtotal", "total_amount"])

    def __str__(self) -> str:
        return f"Order #{self.order_number} ({self.user.username})"


class OrderItem(models.Model):
    """Line items attached to an order."""

    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name="items",
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    product_name = models.CharField(max_length=255)
    material = models.CharField(max_length=100, blank=True, null=True)
    grade = models.CharField(max_length=100, blank=True, null=True)
    quantity = models.PositiveIntegerField(default=1)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)

    def get_cost(self) -> Decimal:
        return Decimal(self.quantity) * self.unit_price

    def save(self, *args: Any, **kwargs: Any) -> None:
        super().save(*args, **kwargs)
        self.order.update_totals()

    def __str__(self) -> str:
        return f"{self.quantity} x {self.product_name}"
