[project]
name = "mi-engineering"
version = "0.1.0"
description = "M.I. Engineering Works Website"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "disposable-email-domains>=0.0.244",
    "django>=6.1",
    "django-environ>=0.14.0",
    "django-htmx>=1.29.0",
    "django-jazzmin>=3.0.5",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.4",
    "python-dotenv>=1.2.3",
]

[tool.uv]
package = false
