# Generated by Django 6.1 on 2026-08-31 07:08

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chemical_composition',
            field=models.JSONField(blank=True, default=dict, help_text='JSON format, e.g., {"Carbon (C)": "0.08%", "Chromium (Cr)": "18.00%"}'),
        ),
        migrations.AddField(
            model_name='product',
            name='mechanical_properties',
            field=models.JSONField(blank=True, default=dict, help_text='JSON format, e.g., {"Tensile Strength": "515 MPa", "Yield Strength": "205 MPa"}'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Detailed overview with formatting, lists, and images', verbose_name='Description'),
        ),
    ]
