# Generated by Django 6.1 on 2026-09-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_chemical_composition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Minimum required order quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base price per piece in INR', max_digits=10),
        ),
    ]
