# Generated by Django 6.1 on 2026-09-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_min_order_quantity_product_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='chemical_composition',
            field=models.JSONField(blank=True, default=dict, help_text='e.g., {"Carbon (C)": "0.08%", "Chromium (Cr)": "18.00%"}'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='grade',
            field=models.CharField(blank=True, default='', help_text='e.g. SS304, SS316, Grade 8.8', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='mechanical_properties',
            field=models.JSONField(blank=True, default=dict, help_text='e.g., {"Tensile Strength": "515 MPa", "Yield Strength": "205 MPa"}'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_range',
            field=models.CharField(blank=True, default='', help_text="e.g. M3 to M64 / 1/2' to 4'", max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard',
            field=models.CharField(blank=True, default='', help_text='e.g. ISO 9001, DIN 933, ASTM A193', max_length=150),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(help_text='Property Value (e.g., Galvanized)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='products_pr_is_acti_2fee29_idx'),
        ),
        migrations.AddConstraint(
            model_name='productspecification',
            constraint=models.UniqueConstraint(fields=('product', 'key'), name='unique_product_spec_key'),
        ),
    ]
