# Generated by Django 6.1 on 2026-09-09 17:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_description_alter_category_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='chemical_composition',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', help_text='Chemical breakdown and element percentages', verbose_name='Chemical Composition'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mechanical_properties',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', help_text='Tensile strength, yield strength, elongation, and hardness', verbose_name='Mechanical Properties'),
        ),
    ]
