# Generated by Django 6.1 on 2026-09-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='applications/')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='standard',
        ),
        migrations.AddField(
            model_name='product',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.application'),
        ),
        migrations.AddField(
            model_name='product',
            name='standards',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.standard'),
        ),
    ]
