# Generated by Django 6.1 on 2026-09-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_application_standard_remove_product_standard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_order_quantity',
        ),
    ]
