# Generated by Django 6.1 on 2026-09-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_min_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='meta_description',
            field=models.TextField(blank=True, default='', help_text='SEO Meta Description (optional)'),
        ),
        migrations.AddField(
            model_name='application',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', help_text='SEO Meta Keywords, comma-separated (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='SEO Meta Title (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, default='', help_text='SEO Meta Description (optional)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', help_text='SEO Meta Keywords, comma-separated (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='SEO Meta Title (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, default='', help_text='SEO Meta Description (optional)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', help_text='SEO Meta Keywords, comma-separated (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='SEO Meta Title (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='standard',
            name='meta_description',
            field=models.TextField(blank=True, default='', help_text='SEO Meta Description (optional)'),
        ),
        migrations.AddField(
            model_name='standard',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', help_text='SEO Meta Keywords, comma-separated (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='standard',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='SEO Meta Title (optional)', max_length=255),
        ),
    ]
