# Generated by Django 6.1 on 2026-09-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_application_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={'ordering': ['name']},
        ),
    ]
