# Generated by Django 6.1 on 2026-09-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_application_options_alter_standard_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/')),
                ('meta_title', models.CharField(blank=True, default='', help_text='SEO Meta Title (optional)', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='', help_text='SEO Meta Description (optional)')),
                ('meta_keywords', models.CharField(blank=True, default='', help_text='SEO Meta Keywords, comma-separated (optional)', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='', help_text='e.g. Stainless Steel, Mild Steel, Brass', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.material'),
        ),
    ]
