# Generated by Django 6.1 on 2026-09-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_material_alter_product_material_product_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification_system',
            field=models.CharField(blank=True, choices=[('Inch', 'Inch'), ('MM', 'MM')], default='', help_text='Specification System (Inch or MM)', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='grade',
            field=models.CharField(blank=True, default='', help_text='e.g. SS304, SS316, Grade 8.8 (Inch system often uses Grade)', max_length=150),
        ),
    ]
