# Generated by Django 6.1 on 2026-09-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_specification_system_alter_product_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
    ]
