# Generated by Django 6.1 on 2026-09-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='grade',
            field=models.CharField(blank=True, default='', help_text='Inch uses Grade, MM uses Class. E.g. Grade 8, Class 8.8', max_length=150, verbose_name='Grade / Class'),
        ),
    ]
